services:
  htmlserver:
    build: ./HTMLServer
    env_file: .env
    ports:
      - "27889:1041"
    depends_on:
      - wsserver

  wsserver:
    build: ./WSServer
    env_file: .env
    ports:
      - "27890:3030"
